name: replicate-segfault
on:
  push:
  workflow_dispatch:

jobs:
  cause_segfault:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        np_install: ['openblas', 'mkl']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
      - name: Install segfaulting code
        if: startsWith(matrix.np_install, 'openblas')
        shell: bash -l {0}
        run: |
          python -m pip install numpy
          python -m pip install -vvv .
      - name: Install segfaulting code
        if: startsWith(matrix.np_install, 'mkl')
        shell: bash -l {0}
        run: |
          conda install -y numpy scipy
          python -m pip install --upgrade-strategy only-if-needed -vvv .
      - name: Run segfaulting code on MacOS
        if: startsWith(matrix.os, 'macos')
        shell: bash -l {0}
        run: |
          python cause_segfault.py -n 101 --order 24 # Doesn't segfault
          python cause_segfault.py -n 100 --order 24 # Does segfault
      - name: Run segfaulting code on Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          python cause_segfault.py -n 8420 --order 3 # Doesn't segfault
          python cause_segfault.py -n 8419 --order 3 # Does segfault
